# =============================================================================
# CI Pipeline - Continuous Integration
# =============================================================================
# Triggers on push to any branch and pull requests to main
# Runs linting, testing, building, and artifact creation
# =============================================================================

name: CI Pipeline

on:
  push:
    branches:
      - '*'
    paths-ignore:
      - '**.md'
      - 'docs/**'
  pull_request:
    branches:
      - main
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: '20'
  REGISTRY: ghcr.io
  IMAGE_PREFIX: ${{ github.repository }}

jobs:
  # ===========================================================================
  # Lint Job
  # ===========================================================================
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install dependencies
        run: |
          cd app/api && npm ci
          cd ../frontend && npm ci
          cd ../worker && npm ci

      - name: Run ESLint
        run: |
          cd app/api && npm run lint
          cd ../frontend && npm run lint
          cd ../worker && npm run lint

      - name: Run TypeScript check
        run: |
          cd app/api && npm run typecheck
          cd ../frontend && npm run typecheck

      - name: Lint Dockerfiles
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: infra/docker/Dockerfile.api
          failure-threshold: warning

      - name: Validate Kubernetes manifests
        uses: azure/k8s-lint@v1
        with:
          manifests: |
            infra/k8s/base/*.yaml

  # ===========================================================================
  # Test Job
  # ===========================================================================
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: lint
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: devops
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: devops_platform_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install API dependencies
        working-directory: app/api
        run: npm ci

      - name: Generate Prisma client
        working-directory: app/api
        run: npx prisma generate

      - name: Run API unit tests
        working-directory: app/api
        env:
          DATABASE_URL: postgresql://devops:test_password@localhost:5432/devops_platform_test
          REDIS_URL: redis://localhost:6379/0
          NODE_ENV: test
        run: npm run test:coverage

      - name: Install frontend dependencies
        working-directory: app/frontend
        run: npm ci

      - name: Run frontend tests
        working-directory: app/frontend
        run: npm run test

      - name: Install worker dependencies
        working-directory: app/worker
        run: npm ci

      - name: Run worker tests
        working-directory: app/worker
        run: npm run test

      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
        with:
          files: app/api/coverage/lcov.info,app/frontend/coverage/lcov.info
          fail_ci_if_error: false

  # ===========================================================================
  # Build Job
  # ===========================================================================
  build:
    name: Build Docker Images
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        service: [frontend, api, worker]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/${{ matrix.service }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix=
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: infra/docker/Dockerfile.${{ matrix.service }}
          target: production
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            VITE_API_URL=${{ vars.VITE_API_URL || '' }}

      - name: Export image digest
        if: github.event_name != 'pull_request'
        run: |
          echo "${{ matrix.service }}=${{ steps.meta.outputs.digest }}" >> $GITHUB_OUTPUT
        id: digest

  # ===========================================================================
  # Summary Job
  # ===========================================================================
  summary:
    name: CI Summary
    runs-on: ubuntu-latest
    needs: [lint, test, build]
    if: always()
    steps:
      - name: Check job results
        run: |
          echo "Lint: ${{ needs.lint.result }}"
          echo "Test: ${{ needs.test.result }}"
          echo "Build: ${{ needs.build.result }}"

          if [ "${{ needs.lint.result }}" != "success" ] || \
             [ "${{ needs.test.result }}" != "success" ] || \
             [ "${{ needs.build.result }}" != "success" ]; then
            echo "One or more jobs failed"
            exit 1
          fi

      - name: CI Passed
        run: echo "All CI checks passed successfully!"
