# =============================================================================
# Cleanup Pipeline
# =============================================================================
# Removes old artifacts, images, and preview environments
# Runs weekly on schedule
# =============================================================================

name: Cleanup

on:
  schedule:
    # Run every Sunday at 3 AM UTC
    - cron: '0 3 * * 0'
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Dry run (no actual deletions)'
        required: false
        default: 'true'
        type: boolean

permissions:
  contents: read
  packages: write
  actions: write

env:
  REGISTRY: ghcr.io
  IMAGE_PREFIX: ${{ github.repository }}

jobs:
  # ===========================================================================
  # Clean Old Artifacts
  # ===========================================================================
  clean-artifacts:
    name: Clean Old Artifacts
    runs-on: ubuntu-latest

    steps:
      - name: Delete old workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 30
          keep_minimum_runs: 10

      - name: Delete old artifacts
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: '30 days'
          skip-recent: 5

  # ===========================================================================
  # Clean Old Container Images
  # ===========================================================================
  clean-images:
    name: Clean Old Container Images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [frontend, api, worker]

    steps:
      - name: Delete old container images
        uses: actions/delete-package-versions@v4
        with:
          package-name: ${{ matrix.service }}
          package-type: 'container'
          min-versions-to-keep: 10
          delete-only-untagged-versions: 'true'

      - name: Delete old pre-release images
        uses: actions/delete-package-versions@v4
        with:
          package-name: ${{ matrix.service }}
          package-type: 'container'
          min-versions-to-keep: 5
          ignore-versions: '^v\\d+\\.\\d+\\.\\d+$'

  # ===========================================================================
  # Clean Stale Branches
  # ===========================================================================
  clean-branches:
    name: Clean Stale Branches
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Delete stale branches
        run: |
          # List branches older than 30 days (merged into main)
          STALE_BRANCHES=$(git branch -r --merged origin/main | \
            grep -v 'main' | \
            grep -v 'develop' | \
            grep -v 'HEAD' | \
            sed 's/origin\///')

          if [ "${{ github.event.inputs.dry_run }}" == "true" ]; then
            echo "DRY RUN - Would delete these branches:"
            echo "$STALE_BRANCHES"
          else
            for branch in $STALE_BRANCHES; do
              echo "Deleting branch: $branch"
              git push origin --delete "$branch" || true
            done
          fi

  # ===========================================================================
  # Clean Preview Environments
  # ===========================================================================
  clean-previews:
    name: Clean Preview Environments
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List preview namespaces
        run: |
          echo "Preview environment cleanup would run here"
          echo "This would delete namespaces matching 'preview-*' older than 7 days"

          # Example kubectl command (requires cluster access):
          # kubectl get namespaces -l type=preview \
          #   --sort-by=.metadata.creationTimestamp \
          #   -o jsonpath='{.items[*].metadata.name}'

  # ===========================================================================
  # Summary
  # ===========================================================================
  summary:
    name: Cleanup Summary
    runs-on: ubuntu-latest
    needs: [clean-artifacts, clean-images, clean-branches, clean-previews]
    if: always()

    steps:
      - name: Cleanup summary
        run: |
          echo "Cleanup completed!"
          echo "Artifacts: ${{ needs.clean-artifacts.result }}"
          echo "Images: ${{ needs.clean-images.result }}"
          echo "Branches: ${{ needs.clean-branches.result }}"
          echo "Previews: ${{ needs.clean-previews.result }}"
