# =============================================================================
# Release Pipeline
# =============================================================================
# Triggers on version tags (v*)
# Builds, tags, and publishes images with version
# Creates GitHub Release with notes
# =============================================================================

name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_PREFIX: ${{ github.repository }}

jobs:
  # ===========================================================================
  # Build and Publish Release Images
  # ===========================================================================
  release-images:
    name: Build Release Images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [frontend, api, worker]

    outputs:
      version: ${{ steps.version.outputs.version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get version from tag
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Version: $VERSION"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/${{ matrix.service }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha,prefix=

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: infra/docker/Dockerfile.${{ matrix.service }}
          target: production
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64

  # ===========================================================================
  # Create GitHub Release
  # ===========================================================================
  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: release-images

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get version
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Generate changelog
        id: changelog
        run: |
          # Get previous tag
          PREV_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")

          if [ -z "$PREV_TAG" ]; then
            CHANGELOG=$(git log --oneline --no-decorate)
          else
            CHANGELOG=$(git log --oneline --no-decorate $PREV_TAG..HEAD)
          fi

          # Escape for GitHub Actions
          CHANGELOG="${CHANGELOG//'%'/'%25'}"
          CHANGELOG="${CHANGELOG//$'\n'/'%0A'}"
          CHANGELOG="${CHANGELOG//$'\r'/'%0D'}"

          echo "changelog=$CHANGELOG" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.version.outputs.version }}
          name: Release ${{ steps.version.outputs.version }}
          body: |
            ## What's Changed

            ${{ steps.changelog.outputs.changelog }}

            ## Docker Images

            ```bash
            # Pull release images
            docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/frontend:${{ steps.version.outputs.version }}
            docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/api:${{ steps.version.outputs.version }}
            docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/worker:${{ steps.version.outputs.version }}
            ```

            ## Deployment

            ```bash
            # Deploy with Kustomize
            cd infra/k8s/overlays/prod
            kustomize edit set image \
              ghcr.io/devops-platform-master/frontend=${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/frontend:${{ steps.version.outputs.version }} \
              ghcr.io/devops-platform-master/api=${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/api:${{ steps.version.outputs.version }} \
              ghcr.io/devops-platform-master/worker=${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/worker:${{ steps.version.outputs.version }}
            kustomize build . | kubectl apply -f -
            ```

            ## Full Changelog

            See [CHANGELOG.md](./CHANGELOG.md) for details.
          draft: false
          prerelease: ${{ contains(steps.version.outputs.version, '-') }}
          generate_release_notes: true

  # ===========================================================================
  # Notify Release
  # ===========================================================================
  notify:
    name: Notify Release
    runs-on: ubuntu-latest
    needs: [release-images, create-release]

    steps:
      - name: Get version
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Send notification
        run: |
          echo "Release ${{ steps.version.outputs.version }} published successfully!"
          # Add Slack/Discord/Email notification here if needed
